--USE [PriceDB]
GO

SELECT [OrderID]
      ,[ClientID]
      ,[OrderDate]
      ,[OrderNum]
      ,[StatusID]
      ,[isCancel]
      ,[isCancelToClient]
      ,[Manufacturer]
      ,[CustomerPriceLogo]
      ,[PriceLogo]
      ,[DetailNumber]
      ,[DetailName]
      ,[MakeLogo]
      ,[DetailID]
      ,[Quantity]
      ,[Price]
      ,[Amount]
      ,[PricePurchase]
      ,[PricePurchaseOrg]
      ,[AmountPurchase]
      ,[Discount]
      ,[PricePurchaseF]
      ,[AmountPurchaseF]
      ,[WeightKG]
      ,[VolumeKG]
      ,[Margin]
      ,[MarginF]
      ,[Profit]
      ,[Income]
      ,[ProfilesDeliveryID]
      ,[ReplacementMakeLogo]
      ,[ReplacementDetailNumber]
      ,[PriceID]
      ,[BasketId]
      ,[EmexOrderID]
      ,[CustomerSubId]
      ,[OrderDetailSubId]
      ,[Reference]
      ,[EmexQuantity]
      ,[OverPricing]
      ,[Warning]
      ,[Flag]
      ,[UserID]
      ,[inDatetime]
      ,[updDatetime]
      ,[ReplacementPrice]
      ,[ParentID]
      ,[ID]
      ,[Invoice]
      ,[FileDate]
      ,[IncomePRC]
      ,[DestinationLogo]
      ,[ClientOrderNum]
      ,[Comment]
      ,[CommissionAmount]
      ,[Reliability]
      ,[Commission]
      ,[ExtraKurs]
      ,[DeliveryPlanDateSupplier]
      ,[DeliveryRestTermSupplier]
      ,[DeliveredDateToSupplier]
      ,[DeliveryDaysReserve]
      ,[DeliveryNextDate]
      ,[DeliveryDateToCustomer]
      ,[DeliveryTermToCustomer]
      ,[DeliveryRestToCustomer]
      ,[Taxes]
      ,[WeightKGAmount]
      ,[VolumeKGAmount]
  into tOrders_20240425
  FROM [dbo].[tOrders]

GO


